apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    role: master
  name: elasticsearch-master
spec:
  podManagementPolicy: Parallel
  replicas: $(MASTER_REPLICAS)
  selector:
    matchLabels:
      app: elasticsearch
      role: master
  serviceName: elasticsearch-master
  template:
    metadata:
      labels:
        role: master
    spec:
      initContainers:
        - name: init-container
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['/bin/sh']
          args:
            - -c
            - >-
              touch /tmp/healthy &&
              sysctl -w vm.max_map_count=${VM_MAX_MAP_COUNT} &&
              sysctl -w fs.file-max=${FS_FILE_MAX}
          env:
            - name: VM_MAX_MAP_COUNT
              valueFrom:
                configMapKeyRef:
                  name: cluster-params
                  key: vm_max_map_count
            - name: FS_FILE_MAX
              valueFrom:
                configMapKeyRef:
                  name: cluster-params
                  key: fs_file_max
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      containers:
        - name: elasticsearch
          image: elasticsearch
          imagePullPolicy: IfNotPresent
          env:
            - name: ES_TMPDIR
              valueFrom:
                configMapKeyRef:
                  name: tmpdir
                  key: tmpdir
            - name: APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: ROLE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['role']
            - name: node.name
              value: '${HOSTNAME}.$(APP)-$(ROLE)'
            - name: node.roles
              value: master
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: elastic.username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: elastic.password
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9300
            timeoutSeconds: 5
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1500Mi
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - name: elasticsearch-yml
              subPath: elasticsearch.yml
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            - name: jvm-options
              subPath: jvm.options
              mountPath: /usr/share/elasticsearch/config/jvm.options.d/jvm.options
            - name: log4j2-properties
              subPath: log4j2.properties
              mountPath: /usr/share/elasticsearch/config/log4j2.properties
            - name: storage
              mountPath: /usr/share/elasticsearch/data
            - name: tmp
              mountPath: /tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 20
      volumes:
        - name: elasticsearch-yml
          configMap:
            name: elasticsearch.yml
        - name: jvm-options
          configMap:
            name: jvm.options
        - name: log4j2-properties
          configMap:
            name: log4j2.properties
        - name: storage
          emptyDir: {}
        - name: tmp
          emptyDir: {}
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: master
  name: elasticsearch-master
spec:
  clusterIP: None
  ports:
    - name: transport
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: elasticsearch
    role: master
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP
